[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  
# Désactiver la détection automatique Next.js pour forcer l'export statique
[build.processing]
  skip_processing = false

# Redirections pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
